name: Test
on:
  pull_request:
  push: 

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.yml
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: docker-compose -f docker-compose-test.yml up
